### ISSUE TITLE
Remove logback and other transitive Dependencies 

### ISSUE THREAD

**Issue by dheeraj-mummareddy** [smart-frameworks/maskit#1]

**Comment by pa1** [comment]
# remove the logback qos dependency
l_logback-classic.jar helps as one of the SLF4J providers on the classpath

Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNGMapConfigurator@506c589e
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.537 sec_
